#!/bin/bash

#to output numbers from a range
for num in {1..10}
do
	echo $num
done


#output as per other languages
declare END=0
for ((i=1;i<=END;i++))
do
    echo $i
done


#to output value from a file
for var in $(cat "$<filename>")
do
	echo $var
done

